packages:
  - packages/*
allowBuilds:
  gl: true
  canvas: true
  core-js: false
  es5-ext: false
  puppeteer: false
overrides:
  mineflayer: workspace:*
  mineflayer-pathfinder: workspace:*
  minecraft-data: workspace:*
  minecraft-protocol: workspace:*
  protodef: workspace:*
  prismarine-item: workspace:*
  prismarine-physics: workspace:*
  prismarine-viewer: workspace:*
  gl: 9.0.0-rc.10
linkWorkspacePackages: true
